server:
  port: 8080

spring:
  application:
    name: spendwise-api

  datasource:
    url: jdbc:mysql://localhost:3306/spendwise_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd'T'HH:mm:ss'Z'
    time-zone: UTC

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970337336763979244226452948404D635166546A576E5A7234753778214125442A47
    expiration-ms: 86400000
    remember-me-expiration-ms: 2592000000

  cors:
    allowed-origins: http://localhost:5173,http://localhost:3000,https://rohitsai2911-git.github.io,https://spendwise-pro.onrender.com

  upload:
    dir: uploads/profiles

logging:
  level:
    com.spendwise: DEBUG
    org.springframework.security: INFO
    org.hibernate.SQL: WARN

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
